// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfzkzuhnlijbsqwfkrbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmemt6dWhubGlqYnNxd2ZrcmJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MTU2NzksImV4cCI6MjA2ODk5MTY3OX0.-oqN-ZG0DmpduBjQ3P0U6G_1G5dNeV2KLIT0akA8mTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});